### ISSUE TITLE
🐞 32 bit support for Electionguard.Encryption

### ISSUE THREAD

**Issue by john-s-morgan** [microsoft/electionguard-core2#347] opened 2023-06-26 20:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

One of our integration vendors requires 32 bit support

### Environment

```markdown
- OS:
```

**Comment by AddressXception** [comment] 2023-07-19 20:14
closing as duplicate of #103

**Closed by AddressXception** 2023-07-19 20:14 UTC
Labels: bug
